version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=memory
      - MYSQL_ROOT_PASSWORD=89911022
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  db:
    driver: local